import { contactLinks, scheduleLink, siteLinks, wosLinks } from '../links.js';

export const FOOTER_TEXT = Object.freeze({
  aria: Object.freeze({
    footer: 'Site Footer and Navigation Directory',
    monogram: 'Hx-313 Insignia',
    sitemap: 'Company navigation',
    socials: 'Social profiles',
    backToTop: 'Back to top of page',
  }),
  headings: Object.freeze({
    systems: 'Selected systems',
    company: 'Company',
    contact: 'Contact',
    base: 'Base & reach',
  }),
  contactNote: 'Available for select product builds, system reviews, and technical advisory.',
  location: Object.freeze({
    basedIn: 'Based in',
    cityCountry: 'Rawalpindi, Pakistan',
    workingScope: 'Working worldwide',
    timezone: 'PKT / UTC+5',
    availability: 'Available for project conversations & selected roles',
    responseLabel: 'Typical response',
    responseValue: 'Within 2 hours',
  }),
  conversation: Object.freeze({
    eyebrow: 'Have a project in mind?',
    title: 'Let’s make the next step clear.',
    description: 'A rough idea is enough. We can shape a practical way forward together.',
    action: 'Start a project',
  }),
  backToTop: 'Back to top',
  navigation: Object.freeze([
    Object.freeze({ label: 'Overview', href: '#top' }),
    Object.freeze({ label: 'Projects', href: '#projects' }),
    Object.freeze({ label: 'About', href: '#about' }),
    Object.freeze({ label: 'Services', href: '#services' }),
    Object.freeze({ label: 'Services in domains', href: '#domains' }),
    Object.freeze({ label: 'Certifications', href: '#certifications' }),
    Object.freeze({ label: 'Tools', href: '#tools' }),
    Object.freeze({ label: 'Contact', href: '#contact' }),
    Object.freeze({ label: 'Testimonials', href: '#testimonials' }),
  ]),
  systems: Object.freeze([
    Object.freeze({
      name: 'WOS Multi-Store Admin',
      role: 'Centralized Multi-Tenant Retail Ops',
      accessibleLabel: 'WOS Multi-Store Admin (Centralized Multi-Tenant Retail Ops)',
      url: wosLinks.adminPanel,
    }),
    Object.freeze({
      name: 'EPOS Terminal Platform',
      role: 'Real-Time Point-of-Sale Engine',
      accessibleLabel: 'EPOS Terminal Platform (Real-Time Point-of-Sale Engine)',
      url: wosLinks.epos,
    }),
    Object.freeze({
      name: 'West Coast Coffee Live',
      role: 'Production E-Commerce Customer Web',
      accessibleLabel: 'West Coast Coffee Live (Production E-Commerce Customer Web)',
      url: wosLinks.customerWebsite,
    }),
  ]),
  connect: Object.freeze([
    Object.freeze({
      id: 'meeting',
      label: 'Book a call',
      action: '30-minute discovery call',
      url: scheduleLink,
    }),
    Object.freeze({
      id: 'whatsapp',
      label: 'WhatsApp',
      action: '0347 5662750',
      url: contactLinks.whatsapp,
    }),
    Object.freeze({
      id: 'phone',
      label: 'Phone',
      action: '0347 5662750',
      url: contactLinks.phone,
    }),
    Object.freeze({
      id: 'email',
      label: 'Email',
      action: 'aliabdullahva313@gmail.com',
      url: contactLinks.email,
    }),
  ]),
  socials: Object.freeze([
    Object.freeze({
      id: 'github',
      name: 'GitHub',
      handle: 'Hx-313',
      ariaLabel: 'Visit GitHub profile for Hx-313 (opens in a new tab)',
      url: siteLinks.github,
    }),
    Object.freeze({
      id: 'linkedin',
      name: 'LinkedIn',
      handle: 'Hafiz Ali Abdullah',
      ariaLabel: 'Visit LinkedIn profile for Hafiz Ali Abdullah (opens in a new tab)',
      url: siteLinks.linkedin,
    }),
    Object.freeze({
      id: 'instagram',
      name: 'Instagram',
      handle: '@ithx313',
      ariaLabel: 'Visit Instagram profile @ithx313 (opens in a new tab)',
      url: siteLinks.instagram,
    }),
  ]),
  colophon: Object.freeze({
    author: 'Hafiz Ali Abdullah',
    handle: 'Hx-313',
    title: 'Flutter + Native Mobile Developer · Node.js Backend Engineer',
    positioning:
      'Building mobile applications, APIs, dashboards, and operational systems for teams that need the whole workflow to work.',
    status: 'Available for project conversations & selected roles',
    timezone: 'PKT / UTC+5 (Rawalpindi)',
    craft: 'Engineered with React, Vite, Motion & Three.js',
    copyright: '© 2026 Hafiz Ali Abdullah. All rights reserved.',
  }),
});