"""Pure renderer — turns the orchestrator's `data` dict into a Markdown string.

This module has NO I/O. It does not touch the network, the filesystem, or
subprocess. That makes it easy to unit-test and to dry-run with `--mock`.

Languages supported: ``en``, ``zh``, ``es``, ``pt``, ``fr``, ``de``, ``ja``,
``ko``, and ``it``. Currency symbol resolution covers the most common
ISO-4217 codes — unknown codes fall back to "{code} " prefix.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any


# ---------------------------------------------------------------------------
# i18n strings (extend as needed)
# ---------------------------------------------------------------------------

STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "action_content": "📝 Draft 1 new piece of content (Pinterest Pin / SEO blog / IG post).",
        "action_more_products": "📦 Only {n} active products — push to 15+ SKUs (healthy niche-store baseline).",
        "action_review_recordings": "📌 Watch 1-2 Clarity recordings to understand real user behavior.",
        "actions_section": "## ⚡ Recommended actions",
        "active_products": "Active products",
        "all_time_orders": "All-time orders",
        "aov": "Average order value (AOV)",
        "avg_rating": "Average rating",
        "bot_sessions": "Bot sessions",
        "browser": "Browser",
        "clarity_link": "Clarity Dashboard",
        "country": "Country",
        "cvr": "Conversion rate (CVR)",
        "data_date": "Data date",
        "data_sources": "Data sources",
        "dead_clicks": "**Dead Clicks** — user clicked something that didn't respond",
        "device": "Device",
        "dim": "Dimension",
        "engagement": "Avg engagement time",
        "excessive_scroll": "**Excessive Scroll** — user scrolling looking for missing info",
        "footer": "_📌 Auto-generated by AI._",
        "generated_at": "Generated at",
        "insight_default": "💤 Light data day, most metrics at baseline; no anomalies.",
        "insight_js": "🐛 {n} JS error(s) — page errors may be silently breaking conversion.",
        "insight_rage": "⚠️ {n} Rage Click(s) detected — users frustrated by a broken element. Investigate immediately.",
        "insight_scroll_high": "✨ Scroll depth {pct}% — users read deeply, content layout is working.",
        "insight_scroll_low": "⚠️ Scroll depth only {pct}% — page too long or above-the-fold isn't compelling.",
        "insight_traffic_no_orders": "💡 {sessions} real visitors, 0 orders — normal for early niche stores; check whether traffic is on-target.",
        "insight_zero_traffic": "💡 Zero traffic yesterday — no acquisition channel is running yet. Push content/SEO today.",
        "insights_section": "## 💡 Today's insights",
        "js_errors": "**JS Errors** — page-level JavaScript errors",
        "kpi_health": "Health",
        "kpi_metric": "Metric",
        "kpi_section": "## 💰 Core KPIs",
        "kpi_value": "Value",
        "link": "Link",
        "links_section": "## 📍 Quick links",
        "no_data": "_(no data)_",
        "orders": "Orders",
        "page": "Page",
        "paid_orders": "Paid orders",
        "popular_pages": "### 🔥 Top 5 popular pages",
        "quick_backs": "**Quick Backs** — visitor bounced within seconds",
        "rage_clicks": "**Rage Clicks** — repeated clicks on the same broken element",
        "rating_dist": "**Rating distribution**",
        "referrer": "Referrer",
        "referrers_section": "### 📍 Referrers",
        "revenue": "Revenue",
        "review_total": "Total reviews",
        "reviews_section": "## ⭐ Reviews (Judge.me)",
        "scroll_depth": "Avg scroll depth",
        "section_unavailable": "_Section unavailable: {reason}_",
        "sessions": "Real-user sessions",
        "shopify_admin": "Shopify Admin",
        "storefront": "Storefront",
        "title": "📊 {store} Daily Report — {date}",
        "tool": "Tool",
        "traffic_section": "## 🌍 Traffic profile (Clarity)",
        "ux_check": "Check",
        "ux_count": "Count",
        "ux_intro": "> All five signals measure 'did users get frustrated and bounce'. Lower is better; 0 is ideal.",
        "ux_meaning": "What it means",
        "ux_section": "## 🐛 UX health (Clarity)",
        "ux_status": "Status",
        "views": "Views",
    },
    "zh": {
        "action_content": "📝 当天产出 1 条新内容（Pinterest Pin / SEO 博客 / IG 帖子）。",
        "action_more_products": "📦 在售商品仅 {n} 件 — 建议补到 15+ 个 SKU（细分店铺的健康基线）。",
        "action_review_recordings": "📌 看 1-2 段 Clarity 用户录屏，了解真实行为。",
        "actions_section": "## ⚡ 今日建议动作",
        "active_products": "在售商品数",
        "all_time_orders": "历史累计订单",
        "aov": "客单价（AOV）",
        "avg_rating": "平均评分",
        "bot_sessions": "机器人会话",
        "browser": "浏览器",
        "clarity_link": "Clarity 控制台",
        "country": "国家",
        "cvr": "转化率（CVR）",
        "data_date": "数据日期",
        "data_sources": "数据来源",
        "dead_clicks": "**Dead Clicks 无效点击** — 用户点了没有响应的元素",
        "device": "设备",
        "dim": "维度",
        "engagement": "平均互动时长",
        "excessive_scroll": "**Excessive Scroll 过度滚动** — 用户在页面里找不到想要的信息",
        "footer": "_📌 由 AI 自动生成。_",
        "generated_at": "生成时间",
        "insight_default": "💤 数据平稳，绝大多数指标处于基线，未见异常。",
        "insight_js": "🐛 {n} 个 JS 报错 — 页面错误可能在悄悄拖累转化。",
        "insight_rage": "⚠️ 检测到 {n} 次 Rage Click — 用户被某个失效元素惹毛了，请立刻排查。",
        "insight_scroll_high": "✨ 滚动深度 {pct}% — 用户深度阅读，内容布局有效。",
        "insight_scroll_low": "⚠️ 滚动深度仅 {pct}% — 页面过长或首屏不够吸引人。",
        "insight_traffic_no_orders": "💡 {sessions} 位真实访客、0 订单 — 早期细分店铺常见，先检查流量是否精准。",
        "insight_zero_traffic": "💡 昨日零流量 — 还没有任何获客渠道在运作，今天先推内容/SEO。",
        "insights_section": "## 💡 今日洞察",
        "js_errors": "**JS Errors 脚本报错** — 页面级 JavaScript 异常",
        "kpi_health": "健康度",
        "kpi_metric": "指标",
        "kpi_section": "## 💰 核心 KPI",
        "kpi_value": "数值",
        "link": "链接",
        "links_section": "## 📍 快捷链接",
        "no_data": "_（暂无数据）_",
        "orders": "订单数",
        "page": "页面",
        "paid_orders": "已支付订单",
        "popular_pages": "### 🔥 Top 5 热门页面",
        "quick_backs": "**Quick Backs 秒退** — 用户进入页面几秒内就退出",
        "rage_clicks": "**Rage Clicks 暴力点击** — 用户对同一个失效元素反复点击",
        "rating_dist": "**评分分布**",
        "referrer": "来源",
        "referrers_section": "### 📍 流量来源",
        "revenue": "营收",
        "review_total": "评价总数",
        "reviews_section": "## ⭐ 商品评价（Judge.me）",
        "scroll_depth": "平均滚动深度",
        "section_unavailable": "_本节不可用：{reason}_",
        "sessions": "真实用户会话",
        "shopify_admin": "Shopify 后台",
        "storefront": "店铺前台",
        "title": "📊 {store} 每日店铺巡检报告 — {date}",
        "tool": "工具",
        "traffic_section": "## 🌍 流量画像（Clarity）",
        "ux_check": "检查项",
        "ux_count": "次数",
        "ux_intro": "> 下面 5 个指标衡量\"用户是否因为页面问题而沮丧离开\"。数值越低越好，0 为理想值。",
        "ux_meaning": "含义",
        "ux_section": "## 🐛 用户体验健康度（Clarity）",
        "ux_status": "状态",
        "views": "浏览量",
    },
    "es": {
        "action_content": "📝 Redactar 1 nueva pieza de contenido (Pin de Pinterest / blog de SEO / publicación de IG).",
        "action_more_products": "📦 Solo {n} productos activos — intenta llegar a más de 15 SKUs (referencia saludable para tienda de nicho).",
        "action_review_recordings": "📌 Ver 1-2 grabaciones de Clarity para entender el comportamiento real del usuario.",
        "actions_section": "## ⚡ Acciones recomendadas",
        "active_products": "Productos activos",
        "all_time_orders": "Pedidos totales",
        "aov": "Valor promedio del pedido (AOV)",
        "avg_rating": "Calificación promedio",
        "bot_sessions": "Sesiones de bots",
        "browser": "Navegador",
        "clarity_link": "Panel de control de Clarity",
        "country": "País",
        "cvr": "Tasa de conversión (CVR)",
        "data_date": "Fecha de los datos",
        "data_sources": "Fuentes de datos",
        "dead_clicks": "**Dead Clicks** — el usuario hizo clic en algo que no respondió",
        "device": "Dispositivo",
        "dim": "Dimensión",
        "engagement": "Tiempo promedio de interacción",
        "excessive_scroll": "**Excessive Scroll** — el usuario se desplaza buscando información que falta",
        "footer": "_📌 Generado automáticamente por AI._",
        "generated_at": "Generado a las",
        "insight_default": "💤 Día de pocos datos, la mayoría de las métricas están en el nivel base; sin anomalías.",
        "insight_js": "🐛 {n} error(es) de JS — los errores de página pueden estar rompiendo la conversión silenciosamente.",
        "insight_rage": "⚠️ {n} Rage Click(s) detectado(s) — usuarios frustrados por un elemento roto. Investiga inmediatamente.",
        "insight_scroll_high": "✨ Profundidad de desplazamiento {pct}% — los usuarios leen a fondo, el diseño del contenido está funcionando.",
        "insight_scroll_low": "⚠️ Profundidad de desplazamiento solo {pct}% — la página es demasiado larga o la parte superior no es atractiva.",
        "insight_traffic_no_orders": "💡 {sessions} visitantes reales, 0 pedidos — normal para tiendas de nicho en etapa inicial; comprueba si el tráfico está bien dirigido.",
        "insight_zero_traffic": "💡 Tráfico cero ayer — aún no funciona ningún canal de adquisición. Impulsa contenido/SEO hoy.",
        "insights_section": "## 💡 Perspectivas de hoy",
        "js_errors": "**JS Errors** — errores de JavaScript a nivel de página",
        "kpi_health": "Salud",
        "kpi_metric": "Métrica",
        "kpi_section": "## 💰 KPIs principales",
        "kpi_value": "Valor",
        "link": "Enlace",
        "links_section": "## 📍 Enlaces rápidos",
        "no_data": "_(sin datos)_",
        "orders": "Pedidos",
        "page": "Página",
        "paid_orders": "Pedidos pagados",
        "popular_pages": "### 🔥 Top 5 páginas populares",
        "quick_backs": "**Quick Backs** — el visitante rebotó en cuestión de segundos",
        "rage_clicks": "**Rage Clicks** — clics repetidos en el mismo elemento roto",
        "rating_dist": "**Distribución de calificaciones**",
        "referrer": "Referente",
        "referrers_section": "### 📍 Referentes",
        "revenue": "Ingresos",
        "review_total": "Total de reseñas",
        "reviews_section": "## ⭐ Reseñas (Judge.me)",
        "scroll_depth": "Profundidad de desplazamiento promedio",
        "section_unavailable": "_Sección no disponible: {reason}_",
        "sessions": "Sesiones de usuarios reales",
        "shopify_admin": "Shopify Admin",
        "storefront": "Escaparate",
        "title": "📊 Informe diario de {store} — {date}",
        "tool": "Herramienta",
        "traffic_section": "## 🌍 Perfil de tráfico (Clarity)",
        "ux_check": "Comprobación",
        "ux_count": "Recuento",
        "ux_intro": "> Las cinco señales miden 'si los usuarios se frustraron y rebotaron'. Cuanto más bajo, mejor; 0 es ideal.",
        "ux_meaning": "Qué significa",
        "ux_section": "## 🐛 Salud de UX (Clarity)",
        "ux_status": "Estado",
        "views": "Vistas",
    },
    "pt": {
        "action_content": "📝 Rascunhe 1 novo conteúdo (Pinterest Pin / Blog de SEO / Post no IG).",
        "action_more_products": "📦 Apenas {n} produtos ativos — envie mais de 15 SKUs (linha de base saudável para lojas de nicho).",
        "action_review_recordings": "📌 Assista a 1-2 gravações do Clarity para entender o comportamento real do usuário.",
        "actions_section": "## ⚡ Ações recomendadas",
        "active_products": "Produtos ativos",
        "all_time_orders": "Total histórico de pedidos",
        "aov": "Valor médio do pedido (AOV)",
        "avg_rating": "Avaliação média",
        "bot_sessions": "Sessões de bots",
        "browser": "Navegador",
        "clarity_link": "Painel do Clarity",
        "country": "País",
        "cvr": "Taxa de conversão (CVR)",
        "data_date": "Data dos dados",
        "data_sources": "Fontes de dados",
        "dead_clicks": "**Dead Clicks** — o usuário clicou em algo que não respondeu",
        "device": "Dispositivo",
        "dim": "Dimensão",
        "engagement": "Tempo médio de engajamento",
        "excessive_scroll": "**Excessive Scroll** — usuário rolando a página em busca de informações ausentes",
        "footer": "_📌 Gerado automaticamente por IA._",
        "generated_at": "Gerado em",
        "insight_default": "💤 Dia de poucos dados, a maioria das métricas na linha de base; sem anomalias.",
        "insight_js": "🐛 {n} erro(s) de JS — erros de página podem estar prejudicando a conversão silenciosamente.",
        "insight_rage": "⚠️ {n} Rage Click(s) detectado(s) — usuários frustrados por um elemento quebrado. Investigue imediatamente.",
        "insight_scroll_high": "✨ Profundidade de rolagem {pct}% — os usuários leram profundamente, o layout do conteúdo está funcionando.",
        "insight_scroll_low": "⚠️ Profundidade de rolagem apenas {pct}% — página muito longa ou o above-the-fold não é atraente.",
        "insight_traffic_no_orders": "💡 {sessions} visitantes reais, 0 pedidos — normal para lojas de nicho iniciais; verifique se o tráfego é qualificado.",
        "insight_zero_traffic": "💡 Tráfego zero ontem — nenhum canal de aquisição está operando ainda. Impulsione conteúdo/SEO hoje.",
        "insights_section": "## 💡 Insights de hoje",
        "js_errors": "**JS Errors** — erros de JavaScript no nível da página",
        "kpi_health": "Saúde",
        "kpi_metric": "Métrica",
        "kpi_section": "## 💰 KPIs principais",
        "kpi_value": "Valor",
        "link": "Link",
        "links_section": "## 📍 Links rápidos",
        "no_data": "_(sem dados)_",
        "orders": "Pedidos",
        "page": "Página",
        "paid_orders": "Pedidos pagos",
        "popular_pages": "### 🔥 Top 5 páginas populares",
        "quick_backs": "**Quick Backs** — visitante saiu em poucos segundos",
        "rage_clicks": "**Rage Clicks** — cliques repetidos no mesmo elemento quebrado",
        "rating_dist": "**Distribuição de avaliações**",
        "referrer": "Referenciador",
        "referrers_section": "### 📍 Referenciadores",
        "revenue": "Receita",
        "review_total": "Total de avaliações",
        "reviews_section": "## ⭐ Avaliações (Judge.me)",
        "scroll_depth": "Profundidade média de rolagem",
        "section_unavailable": "_Seção indisponível: {reason}_",
        "sessions": "Sessões de usuários reais",
        "shopify_admin": "Shopify Admin",
        "storefront": "Vitrine",
        "title": "📊 Relatório Diário da {store} — {date}",
        "tool": "Ferramenta",
        "traffic_section": "## 🌍 Perfil de tráfego (Clarity)",
        "ux_check": "Verificação",
        "ux_count": "Contagem",
        "ux_intro": "> Todos os cinco sinais medem 'se os usuários ficaram frustrados e saíram'. Menor é melhor; 0 é o ideal.",
        "ux_meaning": "O que significa",
        "ux_section": "## 🐛 Saúde de UX (Clarity)",
        "ux_status": "Status",
        "views": "Visualizações",
    },
    "fr": {
        "action_content": "📝 Rédiger 1 nouveau contenu (Pinterest Pin / blog SEO / post IG).",
        "action_more_products": "📦 Seulement {n} produits actifs — passer à 15+ SKU (référence saine pour une boutique de niche).",
        "action_review_recordings": "📌 Regarder 1-2 enregistrements Clarity pour comprendre le comportement réel des utilisateurs.",
        "actions_section": "## ⚡ Actions recommandées",
        "active_products": "Produits actifs",
        "all_time_orders": "Commandes totales",
        "aov": "Valeur moyenne des commandes (AOV)",
        "avg_rating": "Note moyenne",
        "bot_sessions": "Sessions de bots",
        "browser": "Navigateur",
        "clarity_link": "Tableau de bord Clarity",
        "country": "Pays",
        "cvr": "Taux de conversion (CVR)",
        "data_date": "Date des données",
        "data_sources": "Sources de données",
        "dead_clicks": "**Dead Clicks** — l'utilisateur a cliqué sur quelque chose qui n'a pas répondu",
        "device": "Appareil",
        "dim": "Dimension",
        "engagement": "Temps d'engagement moyen",
        "excessive_scroll": "**Excessive Scroll** — l'utilisateur fait défiler en cherchant une info manquante",
        "footer": "_📌 Généré automatiquement par l'IA._",
        "generated_at": "Généré à",
        "insight_default": "💤 Journée de données faible, la plupart des mesures sont à la base ; pas d'anomalies.",
        "insight_js": "🐛 {n} erreur(s) JS — les erreurs de page peuvent briser silencieusement la conversion.",
        "insight_rage": "⚠️ {n} Rage Click(s) détecté(s) — utilisateurs frustrés par un élément cassé. Enquêter immédiatement.",
        "insight_scroll_high": "✨ Profondeur de défilement {pct}% — les utilisateurs lisent en profondeur, la mise en page du contenu fonctionne.",
        "insight_scroll_low": "⚠️ Profondeur de défilement de seulement {pct}% — page trop longue ou le contenu au-dessus de la ligne de flottaison n'est pas convaincant.",
        "insight_traffic_no_orders": "💡 {sessions} visiteurs réels, 0 commande — normal pour les boutiques de niche débutantes ; vérifiez si le trafic est ciblé.",
        "insight_zero_traffic": "💡 Zéro trafic hier — aucun canal d'acquisition ne fonctionne encore. Poussez le contenu/SEO aujourd'hui.",
        "insights_section": "## 💡 Aperçus du jour",
        "js_errors": "**JS Errors** — erreurs JavaScript au niveau de la page",
        "kpi_health": "Santé",
        "kpi_metric": "Mesure",
        "kpi_section": "## 💰 KPI principaux",
        "kpi_value": "Valeur",
        "link": "Lien",
        "links_section": "## 📍 Liens rapides",
        "no_data": "_(aucune donnée)_",
        "orders": "Commandes",
        "page": "Page",
        "paid_orders": "Commandes payées",
        "popular_pages": "### 🔥 Top 5 des pages populaires",
        "quick_backs": "**Quick Backs** — le visiteur a quitté la page après quelques secondes",
        "rage_clicks": "**Rage Clicks** — clics répétés sur le même élément cassé",
        "rating_dist": "**Répartition des notes**",
        "referrer": "Référent",
        "referrers_section": "### 📍 Référents",
        "revenue": "Chiffre d'affaires",
        "review_total": "Total des avis",
        "reviews_section": "## ⭐ Avis (Judge.me)",
        "scroll_depth": "Profondeur de défilement moyenne",
        "section_unavailable": "_Section non disponible : {reason}_",
        "sessions": "Sessions d'utilisateurs réels",
        "shopify_admin": "Admin Shopify",
        "storefront": "Storefront",
        "title": "📊 Rapport quotidien {store} — {date}",
        "tool": "Outil",
        "traffic_section": "## 🌍 Profil du trafic (Clarity)",
        "ux_check": "Contrôle",
        "ux_count": "Nombre",
        "ux_intro": "> Ces cinq signaux mesurent si 'les utilisateurs ont été frustrés et sont partis'. Plus le chiffre est bas, mieux c'est ; 0 est l'idéal.",
        "ux_meaning": "Signification",
        "ux_section": "## 🐛 Santé UX (Clarity)",
        "ux_status": "Statut",
        "views": "Vues",
    },
    "de": {
        "action_content": "📝 Entwerfen Sie 1 neues Inhaltselement (Pinterest-Pin / SEO-Blog / IG-Post).",
        "action_more_products": "📦 Nur {n} aktive Produkte – erhöhen Sie auf 15+ SKUs (gesunde Basis für einen Nischen-Store).",
        "action_review_recordings": "📌 Sehen Sie sich 1-2 Clarity-Aufzeichnungen an, um das echte Nutzerverhalten zu verstehen.",
        "actions_section": "## ⚡ Empfohlene Maßnahmen",
        "active_products": "Aktive Produkte",
        "all_time_orders": "Bestellungen insgesamt",
        "aov": "Durchschnittlicher Bestellwert (AOV)",
        "avg_rating": "Durchschnittliche Bewertung",
        "bot_sessions": "Bot-Sitzungen",
        "browser": "Browser",
        "clarity_link": "Clarity Dashboard",
        "country": "Land",
        "cvr": "Conversion-Rate (CVR)",
        "data_date": "Datumsbereich",
        "data_sources": "Datenquellen",
        "dead_clicks": "**Dead Clicks** – Benutzer hat auf etwas geklickt, das nicht reagiert hat",
        "device": "Gerät",
        "dim": "Dimension",
        "engagement": "Durchschn. Interaktionsdauer",
        "excessive_scroll": "**Excessive Scroll** – Benutzer scrollt auf der Suche nach fehlenden Informationen",
        "footer": "_📌 Automatisch von KI generiert._",
        "generated_at": "Generiert am",
        "insight_default": "💤 Tag mit wenig Daten, die meisten Metriken liegen im Basisbereich; keine Anomalien.",
        "insight_js": "🐛 {n} JS-Fehler – Seitenfehler können die Conversion unbemerkt beeinträchtigen.",
        "insight_rage": "⚠️ {n} Rage Click(s) erkannt – Benutzer sind frustriert über ein fehlerhaftes Element. Sofort untersuchen.",
        "insight_scroll_high": "✨ Scrolltiefe {pct}% – Benutzer lesen aufmerksam, das Inhaltslayout funktioniert.",
        "insight_scroll_low": "⚠️ Scrolltiefe nur {pct}% – Seite zu lang oder Above-the-fold ist nicht überzeugend.",
        "insight_traffic_no_orders": "💡 {sessions} echte Besucher, 0 Bestellungen – normal für junge Nischen-Stores; prüfen Sie, ob der Traffic zielgerichtet ist.",
        "insight_zero_traffic": "💡 Gestern kein Traffic – es läuft noch kein Akquisitionskanal. Heute Content/SEO vorantreiben.",
        "insights_section": "## 💡 Heutige Insights",
        "js_errors": "**JS Errors** – JavaScript-Fehler auf Seitenebene",
        "kpi_health": "Gesundheit",
        "kpi_metric": "Metrik",
        "kpi_section": "## 💰 Kern-KPIs",
        "kpi_value": "Wert",
        "link": "Link",
        "links_section": "## 📍 Quick-Links",
        "no_data": "_(keine Daten)_",
        "orders": "Bestellungen",
        "page": "Seite",
        "paid_orders": "Bezahlte Bestellungen",
        "popular_pages": "### 🔥 Top 5 beliebte Seiten",
        "quick_backs": "**Quick Backs** – Besucher ist innerhalb von Sekunden wieder abgesprungen",
        "rage_clicks": "**Rage Clicks** – wiederholte Klicks auf dasselbe defekte Element",
        "rating_dist": "**Bewertungsverteilung**",
        "referrer": "Referrer",
        "referrers_section": "### 📍 Referrer",
        "revenue": "Umsatz",
        "review_total": "Bewertungen insgesamt",
        "reviews_section": "## ⭐ Bewertungen (Judge.me)",
        "scroll_depth": "Durchschn. Scrolltiefe",
        "section_unavailable": "_Abschnitt nicht verfügbar: {reason}_",
        "sessions": "Sitzungen echter Nutzer",
        "shopify_admin": "Shopify Admin",
        "storefront": "Storefront",
        "title": "📊 {store} Täglicher Bericht — {date}",
        "tool": "Tool",
        "traffic_section": "## 🌍 Traffic-Profil (Clarity)",
        "ux_check": "Prüfung",
        "ux_count": "Anzahl",
        "ux_intro": "> Alle fünf Signale messen, ob Benutzer frustriert waren und abgesprungen sind. Niedriger ist besser; 0 ist ideal.",
        "ux_meaning": "Bedeutung",
        "ux_section": "## 🐛 UX-Gesundheit (Clarity)",
        "ux_status": "Status",
        "views": "Aufrufe",
    },
    "ja": {
        "action_content": "📝 新しいコンテンツ（Pinterest Pin / SEO ブログ / IG 投稿）を 1 つ作成する。",
        "action_more_products": "📦 公開中の商品は {n} 点のみです — 15 個以上の SKU に増やしましょう（健全なニッチストアの基準）。",
        "action_review_recordings": "📌 実際のユーザー行動を理解するために、1 〜 2 個の Clarity 録画を確認する。",
        "actions_section": "## ⚡ 推奨アクション",
        "active_products": "公開中の商品",
        "all_time_orders": "通算注文数",
        "aov": "平均注文金額 (AOV)",
        "avg_rating": "平均評価",
        "bot_sessions": "ボットセッション",
        "browser": "ブラウザ",
        "clarity_link": "Clarity ダッシュボード",
        "country": "国",
        "cvr": "コンバージョン率 (CVR)",
        "data_date": "データ日付",
        "data_sources": "データソース",
        "dead_clicks": "**Dead Clicks** — 反応しない何かをユーザーがクリックしました",
        "device": "デバイス",
        "dim": "ディメンション",
        "engagement": "平均エンゲージメント時間",
        "excessive_scroll": "**Excessive Scroll** — ユーザーが不足している情報を探してスクロールしています",
        "footer": "_📌 AI によって自動生成されました。_",
        "generated_at": "生成日時",
        "insight_default": "💤 データが少ない日です。ほとんどの指標が基準値内にあり、異常はありません。",
        "insight_js": "🐛 {n} 件の JS Errors — ページエラーが密かにコンバージョンを妨げている可能性があります。",
        "insight_rage": "⚠️ {n} 件の Rage Clicks を検出しました — ユーザーが壊れた要素に不満を感じています。すぐに調査してください。",
        "insight_scroll_high": "✨ スクロール深度 {pct}% — ユーザーは深く読み込んでおり、コンテンツのレイアウトは効果的です。",
        "insight_scroll_low": "⚠️ スクロール深度はわずか {pct}% です — ページが長すぎるか、ファーストビューが魅力的ではありません。",
        "insight_traffic_no_orders": "💡 {sessions} 人の実際の訪問者、0 件の注文 — 立ち上げ初期のニッチストアでは一般的です。トラフィックがターゲットに合っているか確認してください。",
        "insight_zero_traffic": "💡 昨日のトラフィックはゼロでした — まだ獲得チャネルが稼働していません。今日はコンテンツ制作や SEO を進めましょう。",
        "insights_section": "## 💡 本日のインサイト",
        "js_errors": "**JS Errors** — ページレベルの JavaScript エラー",
        "kpi_health": "健全性",
        "kpi_metric": "指標",
        "kpi_section": "## 💰 主要 KPI",
        "kpi_value": "値",
        "link": "リンク",
        "links_section": "## 📍 クイックリンク",
        "no_data": "_(データなし)_",
        "orders": "注文数",
        "page": "ページ",
        "paid_orders": "支払い済み注文数",
        "popular_pages": "### 🔥 人気ページ TOP5",
        "quick_backs": "**Quick Backs** — 訪問者が数秒以内に直帰しました",
        "rage_clicks": "**Rage Clicks** — 壊れた同じ要素をユーザーが繰り返しクリックしました",
        "rating_dist": "**評価の分布**",
        "referrer": "リファラー",
        "referrers_section": "### 📍 リファラー",
        "revenue": "売上",
        "review_total": "総レビュー数",
        "reviews_section": "## ⭐ レビュー (Judge.me)",
        "scroll_depth": "平均スクロール深度",
        "section_unavailable": "_セクションを利用できません：{reason}_",
        "sessions": "実際のユーザーセッション",
        "shopify_admin": "Shopify 管理画面",
        "storefront": "ストアフロント",
        "title": "📊 {store} 日次レポート — {date}",
        "tool": "ツール",
        "traffic_section": "## 🌍 トラフィックプロファイル (Clarity)",
        "ux_check": "チェック項目",
        "ux_count": "回数",
        "ux_intro": "> 5 つのシグナルはすべて「ユーザーが不満を感じて直帰したか」を測定します。数値が低いほど良く、0 が理想的です。",
        "ux_meaning": "意味",
        "ux_section": "## 🐛 UX の健全性 (Clarity)",
        "ux_status": "ステータス",
        "views": "閲覧数",
    },
    "ko": {
        "action_content": "📝 1개의 새로운 콘텐츠 초안 작성 (Pinterest Pin / SEO 블로그 / IG 게시물).",
        "action_more_products": "📦 활성 제품이 {n}개뿐입니다 — 15개 이상의 SKU로 늘리십시오 (건강한 니치 스토어 기준선).",
        "action_review_recordings": "📌 실제 사용자 행동을 이해하기 위해 1-2개의 Clarity 녹화물을 시청하십시오.",
        "actions_section": "## ⚡ 권장 조치",
        "active_products": "활성 제품",
        "all_time_orders": "누적 주문",
        "aov": "평균 주문 가치 (AOV)",
        "avg_rating": "평균 평점",
        "bot_sessions": "봇 세션",
        "browser": "브라우저",
        "clarity_link": "Clarity 대시보드",
        "country": "국가",
        "cvr": "전환율 (CVR)",
        "data_date": "데이터 날짜",
        "data_sources": "데이터 소스",
        "dead_clicks": "**Dead Clicks** — 사용자가 응답하지 않는 요소를 클릭함",
        "device": "기기",
        "dim": "차원",
        "engagement": "평균 참여 시간",
        "excessive_scroll": "**Excessive Scroll** — 사용자가 누락된 정보를 찾기 위해 과도하게 스크롤함",
        "footer": "_📌 AI에 의해 자동 생성되었습니다._",
        "generated_at": "생성 일시",
        "insight_default": "💤 데이터가 적은 날입니다. 대부분의 지표가 기준선에 있으며 이상 징후가 없습니다.",
        "insight_js": "🐛 {n}개의 JS 오류 — 페이지 오류가 조용히 전환을 방해하고 있을 수 있습니다.",
        "insight_rage": "⚠️ {n}개의 Rage Click 감지 — 사용자가 고장난 요소로 인해 불만을 느끼고 있습니다. 즉시 조사하십시오.",
        "insight_scroll_high": "✨ 스크롤 깊이 {pct}% — 사용자가 깊이 있게 읽고 있으며 콘텐츠 레이아웃이 효과적입니다.",
        "insight_scroll_low": "⚠️ 스크롤 깊이 {pct}%뿐임 — 페이지가 너무 길거나 상단 영역이 매력적이지 않습니다.",
        "insight_traffic_no_orders": "💡 실제 방문자 {sessions}명, 주문 0건 — 초기 니치 스토어에서는 정상입니다. 트래픽이 타겟에 맞는지 확인하십시오.",
        "insight_zero_traffic": "💡 어제 트래픽 0건 — 아직 운영 중인 유입 채널이 없습니다. 오늘 콘텐츠/SEO를 추진하십시오.",
        "insights_section": "## 💡 오늘의 인사이트",
        "js_errors": "**JS Errors** — 페이지 수준의 JavaScript 오류",
        "kpi_health": "건강 상태",
        "kpi_metric": "지표",
        "kpi_section": "## 💰 핵심 KPI",
        "kpi_value": "값",
        "link": "링크",
        "links_section": "## 📍 빠른 링크",
        "no_data": "_(데이터 없음)_",
        "orders": "주문",
        "page": "페이지",
        "paid_orders": "결제 완료 주문",
        "popular_pages": "### 🔥 인기 페이지 Top 5",
        "quick_backs": "**Quick Backs** — 방문자가 몇 초 내에 이탈함",
        "rage_clicks": "**Rage Clicks** — 동일한 고장난 요소에 대한 반복적인 클릭",
        "rating_dist": "**평점 분포**",
        "referrer": "리퍼러",
        "referrers_section": "### 📍 리퍼러",
        "revenue": "매출",
        "review_total": "총 리뷰 수",
        "reviews_section": "## ⭐ 리뷰 (Judge.me)",
        "scroll_depth": "평균 스크롤 깊이",
        "section_unavailable": "_섹션 사용 불가: {reason}_",
        "sessions": "실제 사용자 세션",
        "shopify_admin": "Shopify 관리자",
        "storefront": "스토어프론트",
        "title": "📊 {store} 일일 보고서 — {date}",
        "tool": "도구",
        "traffic_section": "## 🌍 트래픽 프로필 (Clarity)",
        "ux_check": "확인 사항",
        "ux_count": "횟수",
        "ux_intro": "> 5가지 신호 모두 '사용자가 불만을 느끼고 이탈했는가'를 측정합니다. 낮을수록 좋으며 0이 이상적입니다.",
        "ux_meaning": "의미",
        "ux_section": "## 🐛 UX 건강 상태 (Clarity)",
        "ux_status": "상태",
        "views": "조회수",
    },
    "it": {
        "action_content": "📝 Scrivi 1 nuovo contenuto (Pin di Pinterest / blog SEO / post IG).",
        "action_more_products": "📦 Solo {n} prodotti attivi — arriva a più di 15 SKU (base di riferimento sana per un negozio di nicchia).",
        "action_review_recordings": "📌 Guarda 1-2 registrazioni Clarity per capire il comportamento reale degli utenti.",
        "actions_section": "## ⚡ Azioni consigliate",
        "active_products": "Prodotti attivi",
        "all_time_orders": "Ordini totali",
        "aov": "Valore medio dell'ordine (AOV)",
        "avg_rating": "Valutazione media",
        "bot_sessions": "Sessioni bot",
        "browser": "Browser",
        "clarity_link": "Dashboard Clarity",
        "country": "Paese",
        "cvr": "Tasso di conversione (CVR)",
        "data_date": "Data dei dati",
        "data_sources": "Fonti dati",
        "dead_clicks": "**Dead Clicks** — l'utente ha cliccato su qualcosa che non ha risposto",
        "device": "Dispositivo",
        "dim": "Dimensione",
        "engagement": "Tempo medio di interazione",
        "excessive_scroll": "**Excessive Scroll** — l'utente scorre cercando informazioni mancanti",
        "footer": "_📌 Generato automaticamente dall'AI._",
        "generated_at": "Generato il",
        "insight_default": "💤 Giornata di dati scarsi, la maggior parte delle metriche è alla base di riferimento; nessuna anomalia.",
        "insight_js": "🐛 {n} errore(i) JS — gli errori di pagina potrebbero interrompere silenziosamente la conversione.",
        "insight_rage": "⚠️ Rilevato(i) {n} Rage Click — utenti frustrati da un elemento non funzionante. Indaga immediatamente.",
        "insight_scroll_high": "✨ Profondità di scorrimento {pct}% — gli utenti leggono a fondo, il layout dei contenuti funziona.",
        "insight_scroll_low": "⚠️ Profondità di scorrimento solo {pct}% — pagina troppo lunga o above-the-fold non convincente.",
        "insight_traffic_no_orders": "💡 {sessions} visitatori reali, 0 ordini — normale per i nuovi store di nicchia; controlla se il traffico è in target.",
        "insight_zero_traffic": "💡 Zero traffico ieri — nessun canale di acquisizione è ancora attivo. Spingi su contenuti/SEO oggi.",
        "insights_section": "## 💡 Insight di oggi",
        "js_errors": "**JS Errors** — errori JavaScript a livello di pagina",
        "kpi_health": "Salute",
        "kpi_metric": "Metrica",
        "kpi_section": "## 💰 KPI principali",
        "kpi_value": "Valore",
        "link": "Link",
        "links_section": "## 📍 Link rapidi",
        "no_data": "_(nessun dato)_",
        "orders": "Ordini",
        "page": "Pagina",
        "paid_orders": "Ordini pagati",
        "popular_pages": "### 🔥 Le 5 pagine più popolari",
        "quick_backs": "**Quick Backs** — il visitatore è rimasto solo pochi secondi",
        "rage_clicks": "**Rage Clicks** — clic ripetuti sullo stesso elemento non funzionante",
        "rating_dist": "**Distribuzione delle valutazioni**",
        "referrer": "Referrer",
        "referrers_section": "### 📍 Referrer",
        "revenue": "Entrate",
        "review_total": "Recensioni totali",
        "reviews_section": "## ⭐ Recensioni (Judge.me)",
        "scroll_depth": "Profondità media di scorrimento",
        "section_unavailable": "_Sezione non disponibile: {reason}_",
        "sessions": "Sessioni di utenti reali",
        "shopify_admin": "Admin Shopify",
        "storefront": "Storefront",
        "title": "📊 Report giornaliero {store} — {date}",
        "tool": "Strumento",
        "traffic_section": "## 🌍 Profilo del traffico (Clarity)",
        "ux_check": "Controllo",
        "ux_count": "Conteggio",
        "ux_intro": "> Tutti e cinque i segnali misurano se 'gli utenti si sono frustrati e se ne sono andati'. Più basso è, meglio è; 0 è l'ideale.",
        "ux_meaning": "Significato",
        "ux_section": "## 🐛 Salute UX (Clarity)",
        "ux_status": "Stato",
        "views": "Visualizzazioni",
    },
}


CURRENCY_SYMBOLS = {
    "USD": "$", "EUR": "€", "GBP": "£", "JPY": "¥", "CNY": "¥", "AUD": "A$",
    "CAD": "C$", "HKD": "HK$", "SGD": "S$", "INR": "₹", "KRW": "₩", "BRL": "R$",
}


def _money(amount: float, currency_code: str) -> str:
    sym = CURRENCY_SYMBOLS.get(currency_code, f"{currency_code} ")
    return f"{sym}{amount:,.2f}"


def _fmt_seconds(s: int) -> str:
    if s < 60:
        return f"{s}s"
    return f"{s // 60}m {s % 60}s"


def _badge(value: float, good: float, ok: float) -> str:
    if value >= good:
        return "🟢"
    if value >= ok:
        return "🟡"
    return "🔴"


def _zero_badge(n: int) -> str:
    return "🟢" if n == 0 else ("🟡" if n < 3 else "🔴")


_GROWTH_COPY = {
    "en": {
        "heading": "## 🚀 Growth operations",
        "capability": "Capability",
        "decision": "Decision",
        "reason": "Reason",
        "records": "Records",
        "actions": "Pending/executed actions",
        "yes": "Triggered",
        "no": "Not triggered",
        "unknown": "Unknown",
        "new_product": "New products",
        "campaign_recommendation": "7-day Campaign recommendation",
    },
    "zh": {
        "heading": "## 🚀 增长运营动作",
        "capability": "能力",
        "decision": "判断",
        "reason": "原因",
        "records": "记录数",
        "actions": "待处理/已执行动作",
        "yes": "已触发",
        "no": "未触发",
        "unknown": "无法判断",
        "new_product": "新品识别",
        "campaign_recommendation": "7 天 Campaign 推荐",
    },
    "es": {
        "heading": "## 🚀 Operaciones de crecimiento", "capability": "Capacidad", "decision": "Decisión",
        "reason": "Motivo", "records": "Registros", "actions": "Acciones pendientes/ejecutadas",
        "yes": "Activado", "no": "No activado", "unknown": "Desconocido", "new_product": "Nuevos productos",
        "campaign_recommendation": "Recomendación de campaña de 7 días",
    },
    "pt": {
        "heading": "## 🚀 Operações de crescimento", "capability": "Capacidade", "decision": "Decisão",
        "reason": "Motivo", "records": "Registros", "actions": "Ações pendentes/executadas",
        "yes": "Acionado", "no": "Não acionado", "unknown": "Desconhecido", "new_product": "Novos produtos",
        "campaign_recommendation": "Recomendação de campanha de 7 dias",
    },
    "fr": {
        "heading": "## 🚀 Opérations de croissance", "capability": "Capacité", "decision": "Décision",
        "reason": "Motif", "records": "Enregistrements", "actions": "Actions en attente/exécutées",
        "yes": "Déclenché", "no": "Non déclenché", "unknown": "Inconnu", "new_product": "Nouveaux produits",
        "campaign_recommendation": "Recommandation de campagne de 7 jours",
    },
    "de": {
        "heading": "## 🚀 Wachstumsaktionen", "capability": "Funktion", "decision": "Entscheidung",
        "reason": "Grund", "records": "Datensätze", "actions": "Ausstehende/ausgeführte Aktionen",
        "yes": "Ausgelöst", "no": "Nicht ausgelöst", "unknown": "Unbekannt", "new_product": "Neue Produkte",
        "campaign_recommendation": "Empfehlung für eine 7-Tage-Kampagne",
    },
    "ja": {
        "heading": "## 🚀 グロース運用", "capability": "機能", "decision": "判定", "reason": "理由",
        "records": "件数", "actions": "保留中/実行済みアクション", "yes": "トリガー済み", "no": "未トリガー",
        "unknown": "判定不能", "new_product": "新商品", "campaign_recommendation": "7日間キャンペーンの提案",
    },
    "ko": {
        "heading": "## 🚀 성장 운영", "capability": "기능", "decision": "판정", "reason": "이유",
        "records": "건수", "actions": "대기/실행된 작업", "yes": "트리거됨", "no": "트리거되지 않음",
        "unknown": "판정 불가", "new_product": "신상품", "campaign_recommendation": "7일 캠페인 추천",
    },
    "it": {
        "heading": "## 🚀 Operazioni di crescita", "capability": "Capacità", "decision": "Decisione",
        "reason": "Motivo", "records": "Record", "actions": "Azioni in attesa/eseguite",
        "yes": "Attivato", "no": "Non attivato", "unknown": "Sconosciuto", "new_product": "Nuovi prodotti",
        "campaign_recommendation": "Consiglio campagna di 7 giorni",
    },
}

_CAMPAIGN_COPY = {
    "en": ("### Optional seven-day Campaign", "Starting creates drafts only; publishing still requires exact-content approval."),
    "zh": ("### 可选的 7 天 Campaign", "启动只会创建草稿；发布仍需对最终内容逐条精确批准。"),
    "es": ("### Campaña opcional de siete días", "Iniciar solo crea borradores; publicar aún requiere aprobación exacta."),
    "pt": ("### Campanha opcional de sete dias", "Iniciar cria apenas rascunhos; publicar ainda exige aprovação exata."),
    "fr": ("### Campagne facultative de sept jours", "Le démarrage crée uniquement des brouillons ; la publication exige toujours une approbation exacte."),
    "de": ("### Optionale Sieben-Tage-Kampagne", "Der Start erstellt nur Entwürfe; die Veröffentlichung erfordert weiterhin eine exakte Freigabe."),
    "ja": ("### 任意の7日間キャンペーン", "開始しても下書きのみ作成され、公開には最終内容の承認が必要です。"),
    "ko": ("### 선택형 7일 캠페인", "시작하면 초안만 생성되며 게시에는 최종 콘텐츠 승인이 필요합니다."),
    "it": ("### Campagna opzionale di sette giorni", "L'avvio crea solo bozze; la pubblicazione richiede ancora l'approvazione esatta."),
}


def _inline(value: Any) -> str:
    return str(value if value is not None else "—").replace("\n", " ").replace("\r", " ").replace("|", "\\|")


def _render_growth(growth: dict[str, Any], lang: str) -> str:
    copy = _GROWTH_COPY.get(lang, _GROWTH_COPY["en"])
    triggers = growth.get("triggers") or {}
    md = copy["heading"] + "\n\n"
    md += f"| {copy['capability']} | {copy['decision']} | {copy['reason']} | {copy['records']} |\n|---|---|---|---|\n"
    for name in ("new_product", "campaign_recommendation"):
        item = triggers.get(name) or {}
        matched = item.get("matched")
        decision = copy["yes"] if matched is True else copy["no"] if matched is False else copy["unknown"]
        reason = item.get("reason_code") or "NOT_EVALUATED"
        count = len(item.get("source_ids") or [])
        md += f"| {copy[name]} | {decision} | `{reason}` | {count} |\n"
    campaigns = growth.get("campaign_recommendations") or []
    if campaigns:
        campaign_heading, draft_notice = _CAMPAIGN_COPY.get(lang, _CAMPAIGN_COPY["en"])
        md += f"\n{campaign_heading}\n\n"
        for campaign in campaigns:
            product = campaign.get("product") or {}
            plan = campaign.get("recommended_plan") or {}
            title = _inline(product.get("title"))
            recommendation_id = _inline(campaign.get("recommendation_id"))
            decision = _inline(campaign.get("decision"))
            readiness = _inline(campaign.get("publish_readiness"))
            summary = ""
            if plan:
                summary = (
                    f" · {plan.get('horizon_days', '—')}d"
                    f"/{plan.get('recommended_post_count', '—')} posts"
                    f"/{_inline(plan.get('recommended_channel'))}"
                )
            md += f"- **{title}** · `{recommendation_id}` · `{decision}` · `{readiness}`{summary}\n"
            reasons = campaign.get("reason_codes") or []
            blockers = campaign.get("blocker_codes") or []
            options = campaign.get("user_options") or []
            if reasons:
                md += f"  - reasons: {', '.join(f'`{_inline(item)}`' for item in reasons)}\n"
            if blockers:
                md += f"  - blockers: {', '.join(f'`{_inline(item)}`' for item in blockers)}\n"
            if options:
                md += f"  - options: {', '.join(f'`{_inline(item)}`' for item in options)}\n"
            if campaign.get("decision") == "recommended":
                md += f"  - {draft_notice}\n"
    actions = growth.get("actions") or []
    if actions:
        md += f"\n**{copy['actions']}**\n\n"
        for action in actions:
            md += f"- `{action.get('action_key', '—')}` · {action.get('action_type', '—')} · **{action.get('status', '—')}**\n"
    return md + "\n---\n\n"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def render(data: dict[str, Any], config: dict[str, Any]) -> str:
    """Render the daily report Markdown.

    `data` keys:
        store_name, store_domain, currency, date_label, generated_at,
        sources (list[str]), shopify (dict), clarity (dict), judgeme (dict|None),
        clarity_status, judgeme_status (status strings for degradation),
        growth (optional sanitized trigger/action summary)
    """
    lang = (config.get("language") or "en").lower()
    if lang not in STRINGS:
        lang = "en"
    L = STRINGS[lang]
    currency = data.get("currency") or "USD"

    store_name = data.get("store_name") or data.get("store_domain", "Store")
    date_label = data["date_label"]
    sources = data.get("sources", [])
    shopify = data.get("shopify") or {}
    clarity = data.get("clarity") or {}
    judgeme = data.get("judgeme")

    rev = shopify.get("revenue", 0.0)
    orders_count = shopify.get("count", 0)
    paid_count = shopify.get("paid_count", 0)
    aov = shopify.get("aov", 0.0)
    products_count = shopify.get("active_products", 0)
    all_time_orders = shopify.get("all_time_orders", 0)

    sessions = clarity.get("human_sessions", 0)
    bot_sessions = clarity.get("bot_sessions", 0)
    cvr = (orders_count / sessions * 100) if sessions > 0 else 0
    cvr_badge = _badge(cvr, 1.5, 0.5) if sessions else "⚪"

    # ------- Header -------
    md = f"# {L['title'].format(store=store_name, date=date_label)}\n\n"
    md += f"> {L['generated_at']}: {data.get('generated_at', '')}  \n"
    md += f"> {L['data_date']}: **{date_label}**  \n"
    md += f"> {L['data_sources']}: {' + '.join(sources) if sources else '—'}\n\n---\n\n"

    # ------- KPIs -------
    md += L["kpi_section"] + "\n\n"
    md += f"| {L['kpi_metric']} | {L['kpi_value']} | {L['kpi_health']} |\n|---|---|---|\n"
    md += f"| {L['revenue']} | **{_money(rev, currency)}** | {'🟢' if rev > 0 else '⚪'} |\n"
    md += f"| {L['orders']} | **{orders_count}** | {'🟢' if orders_count > 0 else '⚪'} |\n"
    md += f"| {L['paid_orders']} | {paid_count} | — |\n"
    md += f"| {L['aov']} | {_money(aov, currency)} | {_badge(aov, 45, 25) if aov else '⚪'} |\n"
    md += f"| {L['sessions']} | **{sessions}** | {'🟢' if sessions >= 20 else ('🟡' if sessions >= 5 else '🔴')} |\n"
    md += f"| {L['bot_sessions']} | {bot_sessions} | — |\n"
    md += f"| {L['cvr']} | **{cvr:.2f}%** | {cvr_badge} |\n"
    md += f"| {L['active_products']} | {products_count} | {'🟢' if products_count >= 15 else ('🟡' if products_count >= 5 else '🔴')} |\n"
    md += f"| {L['all_time_orders']} | {all_time_orders} | — |\n\n---\n\n"

    # ------- Traffic profile -------
    md += L["traffic_section"] + "\n\n"
    if data.get("clarity_status") == "ok":
        md += f"| {L['dim']} | Top 1 |\n|---|---|\n"
        md += f"| {L['country']} | {clarity.get('top_country', '—')} |\n"
        md += f"| {L['device']} | {clarity.get('top_device', '—')} |\n"
        md += f"| {L['browser']} | {clarity.get('top_browser', '—')} |\n"
        md += f"| {L['scroll_depth']} | {clarity.get('avg_scroll_depth', 0)}% |\n"
        md += f"| {L['engagement']} | {_fmt_seconds(clarity.get('engagement_time_sec', 0))} |\n\n"

        md += L["popular_pages"] + "\n\n"
        if clarity.get("popular_pages"):
            md += f"| # | {L['page']} | {L['views']} |\n|---|---|---|\n"
            domain = data.get("store_domain", "")
            for i, p in enumerate(clarity["popular_pages"][:5], 1):
                url = (p.get("url") or "").replace(f"https://{domain}", "") or "/"
                md += f"| {i} | `{url}` | {p.get('visits', 0)} |\n"
        else:
            md += L["no_data"] + "\n"

        md += "\n" + L["referrers_section"] + "\n\n"
        if clarity.get("referrers"):
            md += f"| {L['referrer']} | Sessions |\n|---|---|\n"
            for r in clarity["referrers"][:5]:
                md += f"| {r.get('name', 'Direct')} | {r.get('sessions', 0)} |\n"
        else:
            md += L["no_data"] + "\n"
    else:
        reason = data.get("clarity_reason") or data.get("clarity_status", "unknown")
        md += L["section_unavailable"].format(reason=reason) + "\n"
    md += "\n---\n\n"

    # ------- UX health -------
    md += L["ux_section"] + "\n\n" + L["ux_intro"] + "\n\n"
    if data.get("clarity_status") == "ok":
        rage = clarity.get("rage_clicks", 0)
        dead = clarity.get("dead_clicks", 0)
        quick = clarity.get("quick_backs", 0)
        jse = clarity.get("js_errors", 0)
        excs = clarity.get("excessive_scroll", 0)

        md += f"| {L['ux_check']} | {L['ux_count']} | {L['ux_status']} |\n|---|---|---|\n"
        md += f"| {L['rage_clicks']} | {rage} | {_zero_badge(rage)} |\n"
        md += f"| {L['dead_clicks']} | {dead} | {'🟢' if dead == 0 else '🟡'} |\n"
        md += f"| {L['quick_backs']} | {quick} | {'🟢' if quick == 0 else '🟡'} |\n"
        md += f"| {L['js_errors']} | {jse} | {'🟢' if jse == 0 else '🔴'} |\n"
        md += f"| {L['excessive_scroll']} | {excs} | {'🟢' if excs == 0 else '🟡'} |\n"
    else:
        reason = data.get("clarity_reason") or data.get("clarity_status", "unknown")
        md += L["section_unavailable"].format(reason=reason) + "\n"
    md += "\n---\n\n"

    # ------- Reviews (only when judgeme returned ok) -------
    if data.get("judgeme_status") == "ok" and judgeme:
        md += L["reviews_section"] + "\n\n"
        md += f"| {L['kpi_metric']} | {L['kpi_value']} |\n|---|---|\n"
        md += f"| {L['review_total']} | **{judgeme.get('total_count', 0)}** |\n"
        md += f"| {L['avg_rating']} | {judgeme.get('average_rating', 0) or '—'} ⭐ |\n\n"
        rd = judgeme.get("rating_distribution") or {}
        if rd:
            md += L["rating_dist"] + ":\n\n"
            for star in [5, 4, 3, 2, 1]:
                n = rd.get(star, 0)
                bar = "█" * n if n > 0 else ""
                md += f"- {star}⭐ {bar} {n}\n"
            md += "\n"
        md += "---\n\n"

    # ------- Deterministic growth triggers and action ledger -------
    if data.get("growth"):
        md += _render_growth(data["growth"], lang)

    # ------- Insights -------
    insights, actions = _build_insights_and_actions(L, lang, sessions, rev, clarity, products_count)
    md += L["insights_section"] + "\n\n"
    for i in insights:
        md += f"- {i}\n"
    md += "\n---\n\n" + L["actions_section"] + "\n\n"
    for i, a in enumerate(actions[:5], 1):
        md += f"{i}. {a}\n"

    # ------- Quick links -------
    md += "\n---\n\n" + L["links_section"] + "\n\n"
    md += f"| {L['tool']} | {L['link']} |\n|---|---|\n"
    domain = data.get("store_domain", "")
    if domain:
        store_handle = domain.replace(".myshopify.com", "")
        md += f"| {L['storefront']} | https://{domain} |\n"
        md += f"| {L['shopify_admin']} | https://admin.shopify.com/store/{store_handle} |\n"
    clarity_pid = config.get("clarity", {}).get("project_id")
    if clarity_pid:
        md += f"| {L['clarity_link']} | https://clarity.microsoft.com/projects/view/{clarity_pid}/dashboard |\n"

    md += "\n" + L["footer"] + "\n"
    return md


def _build_insights_and_actions(
    L: dict[str, str],
    lang: str,
    sessions: int,
    rev: float,
    clarity: dict[str, Any],
    products_count: int,
) -> tuple[list[str], list[str]]:
    insights: list[str] = []
    actions: list[str] = []

    if rev == 0 and sessions == 0:
        insights.append(L["insight_zero_traffic"])
    elif rev == 0 and sessions > 0:
        insights.append(L["insight_traffic_no_orders"].format(sessions=sessions))

    if clarity.get("rage_clicks", 0) > 0:
        insights.append(L["insight_rage"].format(n=clarity["rage_clicks"]))
        actions.append(
            "Fix Rage Click source (Clarity Recordings -> filter `rage_click`)"
        )
    if clarity.get("js_errors", 0) > 0:
        insights.append(L["insight_js"].format(n=clarity["js_errors"]))
        actions.append("Fix JS errors")
    sd = clarity.get("avg_scroll_depth", 0)
    if sd >= 80:
        insights.append(L["insight_scroll_high"].format(pct=sd))
    elif 0 < sd < 50:
        insights.append(L["insight_scroll_low"].format(pct=sd))

    if not insights:
        insights.append(L["insight_default"])
    if not actions:
        if products_count < 10:
            actions.append(L["action_more_products"].format(n=products_count))
        actions.append(L["action_review_recordings"])
        actions.append(L["action_content"])

    return insights, actions
