const assets = Object.freeze({
  cert5816324103Pdf: new URL('../../../../../certifications/Cert5816324103.pdf', import.meta.url).href,
  courseraGgPdf: new URL('../../../../../certifications/Coursera GG2Y2MZOL6ZU.pdf', import.meta.url).href,
  courseraGgPreview: new URL('../../../../../certifications/Coursera GG2Y2MZOL6ZU.png', import.meta.url).href,
  courseraTuPdf: new URL('../../../../../certifications/Coursera TUZAVQAMZ1G1.pdf', import.meta.url).href,
  courseraTuPreview: new URL('../../../../../certifications/Coursera TUZAVQAMZ1G1.png', import.meta.url).href,
  navttcPdf: new URL('../../../../../certifications/navttc.pdf', import.meta.url).href,
  sscPdf: new URL('../../../../../certifications/1 pos in ssc1.pdf', import.meta.url).href,
  urduSpeechPdf: new URL('../../../../../certifications/2nd pos in Urdu soeach.pdf', import.meta.url).href,
  icsPdf: new URL('../../../../../certifications/best achievement in ics.pdf', import.meta.url).href,
  readersClubPdf: new URL('../../../../../certifications/g sec of readers club.pdf', import.meta.url).href,
  classSixPdf: new URL('../../../../../certifications/merit in 6 class pos 1.pdf', import.meta.url).href,
  cricketPdf: new URL('../../../../../certifications/participate in cricket.pdf', import.meta.url).href,
  wafaqPdf: new URL('../../../../../certifications/wafaq ul madaris.pdf', import.meta.url).href,
});

const pdf = (href) => Object.freeze({ type: 'pdf', href });

const image = (src, alt) => Object.freeze({ type: 'image', src, alt });

const record = (value) => Object.freeze({ ...value });

const professionalRecords = Object.freeze([
  record({
    id: 'certiport-java',
    category: 'professional',
    title: 'Java',
    issuer: 'Certiport',
    date: 'Issued March 14, 2025',
    issuerMark: 'CP',
    identifier: 'UoE5-s4Na',
    preview: null,
    document: pdf(assets.cert5816324103Pdf),
    status: 'verified',
  }),
  record({
    id: 'ibm-flutter-dart-mobile-apps',
    category: 'professional',
    title: 'Flutter and Dart: Developing iOS, Android, and Mobile Apps',
    issuer: 'IBM and Coursera',
    date: 'Issued June 11, 2025',
    issuerMark: 'IBM',
    identifier: 'GG2Y2MZOL6ZU',
    preview: image(assets.courseraGgPreview, 'IBM and Coursera certificate for Flutter and Dart mobile app development'),
    document: pdf(assets.courseraGgPdf),
    status: 'verified',
  }),
  record({
    id: 'ibm-introduction-mobile-app-development',
    category: 'professional',
    title: 'Introduction to Mobile App Development',
    issuer: 'IBM and Coursera',
    date: 'Issued June 11, 2025',
    issuerMark: 'IBM',
    identifier: 'TUZAVQAMZ1G1',
    preview: image(assets.courseraTuPreview, 'IBM and Coursera certificate for introduction to mobile app development'),
    document: pdf(assets.courseraTuPdf),
    status: 'verified',
  }),
  record({
    id: 'navttc-android-java-database',
    category: 'professional',
    title: 'Android Java and Database',
    issuer: 'NAVTTC',
    date: 'Completed October 15, 2024',
    issuerMark: 'NAV',
    identifier: 'Prime Minister’s Youth Skills Development Program',
    preview: null,
    document: pdf(assets.navttcPdf),
    status: 'verified',
  }),
]);

const lifetimeRecords = Object.freeze([
  record({
    id: 'askaria-first-position-ssc',
    category: 'lifetime',
    title: 'First position in SSC I',
    issuer: 'Askaria Schools and Colleges',
    date: 'Academic year 2018 to 2019',
    issuerMark: 'AS',
    identifier: 'Certificate of Achievement',
    preview: null,
    document: pdf(assets.sscPdf),
    status: 'documented',
  }),
  record({
    id: 'askaria-urdu-speech',
    category: 'lifetime',
    title: 'Second position in Urdu speech competition',
    issuer: 'Askaria Schools and Colleges',
    date: 'Academic year 2019 to 2020',
    issuerMark: 'AS',
    identifier: 'Certificate of Achievement',
    preview: null,
    document: pdf(assets.urduSpeechPdf),
    status: 'documented',
  }),
  record({
    id: 'askaria-best-achievement-ics',
    category: 'lifetime',
    title: 'Best achievement in board exams',
    issuer: 'Askaria Schools and Colleges',
    date: 'Academic year 2019 to 2020',
    issuerMark: 'AS',
    identifier: 'ICS I',
    preview: null,
    document: pdf(assets.icsPdf),
    status: 'documented',
  }),
  record({
    id: 'askaria-readers-club',
    category: 'lifetime',
    title: 'General Secretary of Readers Club',
    issuer: 'Askaria Schools and Colleges',
    date: 'Academic year 2017 to 2018',
    issuerMark: 'AS',
    identifier: 'Certificate of Achievement',
    preview: null,
    document: pdf(assets.readersClubPdf),
    status: 'documented',
  }),
  record({
    id: 'iqra-quiz-position',
    category: 'lifetime',
    title: 'First position in quiz competition',
    issuer: 'Iqra Huffaz Secondary School',
    date: 'February 28, 2015',
    issuerMark: 'IQ',
    identifier: 'Class 6',
    preview: null,
    document: pdf(assets.classSixPdf),
    status: 'documented',
  }),
  record({
    id: 'askaria-cricket-participation',
    category: 'lifetime',
    title: 'Participation in cricket',
    issuer: 'Askaria Schools and Colleges',
    date: 'December 24, 2019',
    issuerMark: 'AS',
    identifier: 'Certificate of Achievement',
    preview: null,
    document: pdf(assets.cricketPdf),
    status: 'documented',
  }),
  record({
    id: 'wifaq-ul-madaris-hifz',
    category: 'lifetime',
    title: 'Hifz ul Quran with Tajweed',
    issuer: 'Wifaq ul Madaris Al Arabia',
    date: 'Issued June 10, 2013',
    issuerMark: 'WM',
    identifier: 'Certificate 11436',
    preview: null,
    document: pdf(assets.wafaqPdf),
    status: 'documented',
  }),
]);

export const CERTIFICATION_GROUPS = Object.freeze([
  Object.freeze({
    id: 'professional',
    heading: 'Professional certifications',
    ariaLabel: 'Professional certifications archive',
    records: professionalRecords,
  }),
  Object.freeze({
    id: 'lifetime',
    heading: 'Lifetime achievements',
    ariaLabel: 'Lifetime achievements archive',
    records: lifetimeRecords,
  }),
]);
