const assets = Object.freeze({
  certiportJava: new URL('../../../../../certifications/Cert5816324103-1.png', import.meta.url).href,
  courseraGg: new URL('../../../../../certifications/Coursera GG2Y2MZOL6ZU-1.png', import.meta.url).href,
  courseraTu: new URL('../../../../../certifications/Coursera TUZAVQAMZ1G1-1.png', import.meta.url).href,
  navttc: new URL('../../../../../certifications/navttc-1.png', import.meta.url).href,
  ssc: new URL('../../../../../certifications/1 pos in ssc1-1.png', import.meta.url).href,
  urduSpeech: new URL('../../../../../certifications/2nd pos in Urdu soeach-1.png', import.meta.url).href,
  ics: new URL('../../../../../certifications/best achievement in ics-1.png', import.meta.url).href,
  readersClub: new URL('../../../../../certifications/g sec of readers club-1.png', import.meta.url).href,
  classSix: new URL('../../../../../certifications/merit in 6 class pos 1-1.png', import.meta.url).href,
  cricket: new URL('../../../../../certifications/participate in cricket-1.png', import.meta.url).href,
  wafaq: new URL('../../../../../certifications/wafaq ul madaris-1.png', import.meta.url).href,
});

const preview = (src, alt) => Object.freeze({ type: 'image', src, alt });
const credential = (href) => Object.freeze({ type: 'image', href });
const record = (value) => Object.freeze({ ...value });

export const CERTIFICATION_RECORDS = Object.freeze([
  record({
    id: 'certiport-java',
    title: 'Java',
    issuer: 'Certiport',
    date: 'Issued March 14, 2025',
    issuerMark: 'CP',
    identifier: 'UoE5-s4Na',
    preview: preview(assets.certiportJava, 'Certiport Java certification'),
    document: credential(assets.certiportJava),
    status: 'verified',
  }),
  record({
    id: 'ibm-flutter-dart-mobile-apps',
    title: 'Flutter and Dart: Developing iOS, Android, and Mobile Apps',
    issuer: 'IBM and Coursera',
    date: 'Issued June 11, 2025',
    issuerMark: 'IBM',
    identifier: 'GG2Y2MZOL6ZU',
    preview: preview(assets.courseraGg, 'IBM and Coursera certificate for Flutter and Dart mobile app development'),
    document: credential(assets.courseraGg),
    status: 'verified',
  }),
  record({
    id: 'ibm-introduction-mobile-app-development',
    title: 'Introduction to Mobile App Development',
    issuer: 'IBM and Coursera',
    date: 'Issued June 11, 2025',
    issuerMark: 'IBM',
    identifier: 'TUZAVQAMZ1G1',
    preview: preview(assets.courseraTu, 'IBM and Coursera certificate for introduction to mobile app development'),
    document: credential(assets.courseraTu),
    status: 'verified',
  }),
  record({
    id: 'navttc-android-java-database',
    title: 'Android Java and Database',
    issuer: 'NAVTTC',
    date: 'Completed October 15, 2024',
    issuerMark: 'NAV',
    identifier: 'Prime Minister’s Youth Skills Development Program',
    preview: preview(assets.navttc, 'NAVTTC Android Java and Database certificate'),
    document: credential(assets.navttc),
    status: 'verified',
  }),
  record({
    id: 'askaria-first-position-ssc',
    title: 'First position in SSC I',
    issuer: 'Askaria Schools and Colleges',
    date: 'Academic year 2018 to 2019',
    issuerMark: 'AS',
    identifier: 'Certificate of Achievement',
    preview: preview(assets.ssc, 'Askaria Schools and Colleges SSC achievement certificate'),
    document: credential(assets.ssc),
    status: 'documented',
  }),
  record({
    id: 'askaria-urdu-speech',
    title: 'Second position in Urdu speech competition',
    issuer: 'Askaria Schools and Colleges',
    date: 'Academic year 2019 to 2020',
    issuerMark: 'AS',
    identifier: 'Certificate of Achievement',
    preview: preview(assets.urduSpeech, 'Askaria Urdu speech competition certificate'),
    document: credential(assets.urduSpeech),
    status: 'documented',
  }),
  record({
    id: 'askaria-best-achievement-ics',
    title: 'Best achievement in board exams',
    issuer: 'Askaria Schools and Colleges',
    date: 'Academic year 2019 to 2020',
    issuerMark: 'AS',
    identifier: 'ICS I',
    preview: preview(assets.ics, 'Askaria Schools and Colleges board achievement certificate'),
    document: credential(assets.ics),
    status: 'documented',
  }),
  record({
    id: 'askaria-readers-club',
    title: 'General Secretary of Readers Club',
    issuer: 'Askaria Schools and Colleges',
    date: 'Academic year 2017 to 2018',
    issuerMark: 'AS',
    identifier: 'Certificate of Achievement',
    preview: preview(assets.readersClub, 'Askaria Readers Club certificate'),
    document: credential(assets.readersClub),
    status: 'documented',
  }),
  record({
    id: 'iqra-quiz-position',
    title: 'First position in quiz competition',
    issuer: 'Iqra Huffaz Secondary School',
    date: 'February 28, 2015',
    issuerMark: 'IQ',
    identifier: 'Class 6',
    preview: preview(assets.classSix, 'Iqra Huffaz Secondary School quiz certificate'),
    document: credential(assets.classSix),
    status: 'documented',
  }),
  record({
    id: 'askaria-cricket-participation',
    title: 'Participation in cricket',
    issuer: 'Askaria Schools and Colleges',
    date: 'December 24, 2019',
    issuerMark: 'AS',
    identifier: 'Certificate of Achievement',
    preview: preview(assets.cricket, 'Askaria cricket participation certificate'),
    document: credential(assets.cricket),
    status: 'documented',
  }),
  record({
    id: 'wifaq-ul-madaris-hifz',
    title: 'Hifz ul Quran with Tajweed',
    issuer: 'Wifaq ul Madaris Al Arabia',
    date: 'Issued June 10, 2013',
    issuerMark: 'WM',
    identifier: 'Certificate 11436',
    preview: preview(assets.wafaq, 'Wifaq ul Madaris Al Arabia Hifz ul Quran certificate'),
    document: credential(assets.wafaq),
    status: 'documented',
  }),
]);
